const devices = [
  {
    id: 1,
    name: "HKA80",
    modelId: "Z7C",
    codeEAN13CharMaxLen: 12,
    codeITFCharMaxLen: 12,
    codeCode128CharMaxLen: 23,
    codeCode39CharMaxLen: 20,
    codeQRCharMaxLen: 120,
    codePDFCharMaxLen: 120,

    headersXlen: 40,
    footersXlen: 40,
    RifLen: 40,
    RazonSocialLen: 40,
    AdcInfoLen: 40,
    CommentsLen: 40,
    DescLen: 127,
  },
  {
    id: 2,
    name: "HKA112",
    modelId: "Z7A",
    codeEAN13CharMaxLen: 12,
    codeITFCharMaxLen: 20,
    codeCode128CharMaxLen: 20,
    codeCode39CharMaxLen: 20,
    codeQRCharMaxLen: 120,
    codePDFCharMaxLen: false,
    headersXlen: 40,
    footersXlen: 40,
    RifLen: 40,
    RazonSocialLen: 40,
    AdcInfoLen: 40,
    CommentsLen: 40,
    DescLen: 116,
  },
  {
    id: 3,
    name: "SRP-270",
    modelId: "Z1A",
    codeEAN13CharMaxLen: false,
    codeITFCharMaxLen: false,
    codeCode128CharMaxLen: false,
    codeCode39CharMaxLen: false,
    codeQRCharMaxLen: false,
    codePDFCharMaxLen: false,

    headersXlen: 40,
    footersXlen: 40,
    RifLen: 33,
    RazonSocialLen: 40,
    AdcInfoLen: 40,
    CommentsLen: 40,
    DescLen: 120,
  },
  {
    id: 4,
    name: "SRP-350",
    modelId: "Z1B",
    codeEAN13CharMaxLen: 12,
    codeITFCharMaxLen: 31,
    codeCode128CharMaxLen: 32,
    codeCode39CharMaxLen: false,
    codeQRCharMaxLen: false,
    codePDFCharMaxLen: false,

    headersXlen: 40,
    footersXlen: 40,
    RifLen: 47,
    RazonSocialLen: 43,
    AdcInfoLen: 56,
    CommentsLen: 40,
    DescLen: 37,
  },
  {
    id: 5,
    name: "SRP-280",
    modelId: "Z1E",
    codeEAN13CharMaxLen: false,
    codeITFCharMaxLen: false,
    codeCode128CharMaxLen: false,
    codeCode39CharMaxLen: false,
    codeQRCharMaxLen: false,
    codePDFCharMaxLen: false,

    headersXlen: 40,
    footersXlen: 40,
    RifLen: 33,
    RazonSocialLen: 40,
    AdcInfoLen: 40,
    CommentsLen: 40,
    DescLen: 120,
  },
  {
    id: 6,
    name: "SRP-812",
    modelId: "Z1F",
    codeEAN13CharMaxLen: 12,
    codeITFCharMaxLen: 12,
    codeCode128CharMaxLen: 32,
    codeCode39CharMaxLen: 32,
    codeQRCharMaxLen: 120,
    codePDFCharMaxLen: 120,

    headersXlen: 40,
    footersXlen: 40,
    RifLen: 40,
    RazonSocialLen: 40,
    AdcInfoLen: 40,
    CommentsLen: 40,
    DescLen: 127,
  },
  {
    id: 7,
    name: "HSP7000",
    modelId: "ZPA",
    codeEAN13CharMaxLen: 12,
    codeITFCharMaxLen: 20,
    codeCode128CharMaxLen: 20,
    codeCode39CharMaxLen: 20,
    codeQRCharMaxLen: false,
    codePDFCharMaxLen: false,

    headersXlen: 40,
    footersXlen: 40,
    RifLen: 47,
    RazonSocialLen: 43,
    AdcInfoLen: 50,
    CommentsLen: 40,
    DescLen: 120,
  },
  {
    id: 8,
    name: "TALLY 1125",
    modelId: "Z6A",
    codeEAN13CharMaxLen: 12,
    codeITFCharMaxLen: 32,
    codeCode128CharMaxLen: 32,
    codeCode39CharMaxLen: 32,
    codeQRCharMaxLen: false,
    codePDFCharMaxLen: false,

    headersXlen: 0,
    footersXlen: 0,
    RifLen: 0,
    RazonSocialLen: 0,
    AdcInfoLen: 0,
    CommentsLen: 0,
    DescLen: 0,
  },
  {
    id: 9,
    name: "DT-230",
    modelId: "Z6B",
    codeEAN13CharMaxLen: 12,
    codeITFCharMaxLen: 32,
    codeCode128CharMaxLen: 32,
    codeCode39CharMaxLen: 32,
    codeQRCharMaxLen: 122,
    codePDFCharMaxLen: 122,

    headersXlen: 40,
    footersXlen: 40,
    RifLen: 40,
    RazonSocialLen: 40,
    AdcInfoLen: 40,
    CommentsLen: 40,
    DescLen: 127,
  },
  {
    id: 10,
    name: "TALLY 1140",
    modelId: "Z6C",
    codeEAN13CharMaxLen: 12,
    codeITFCharMaxLen: 32,
    codeCode128CharMaxLen: 25,
    codeCode39CharMaxLen: 11,
    codeQRCharMaxLen: false,
    codePDFCharMaxLen: false,

    headersXlen: 0,
    footersXlen: 0,
    RifLen: 0,
    RazonSocialLen: 0,
    AdcInfoLen: 0,
    CommentsLen: 0,
    DescLen: 0,
  },
  {
    id: 11,
    name: "P3100DL",
    modelId: "ZYA",
    codeEAN13CharMaxLen: 12,
    codeITFCharMaxLen: 13,
    codeCode128CharMaxLen: 32,
    codeCode39CharMaxLen: 32,
    codeQRCharMaxLen: 120,
    codePDFCharMaxLen: 120,
    headersXlen: 38,
    footersXlen: 38,
    RifLen: 24,
    RazonSocialLen: 20,
    AdcInfoLen: 33,
    CommentsLen: 27,
    DescLen: 127,
  },
  {
    id: 12,
    name: "PP9",
    modelId: "ZZH",
    codeEAN13CharMaxLen: 12,
    codeITFCharMaxLen: 38,
    codeCode128CharMaxLen: 44,
    codeCode39CharMaxLen: 12,
    codeQRCharMaxLen: 122,
    codePDFCharMaxLen: false,

    headersXlen: 40,
    footersXlen: 40,
    RifLen: 38,
    RazonSocialLen: 34,
    AdcInfoLen: 40,
    CommentsLen: 40,
    DescLen: 120,
  },
  {
    id: 13,
    name: "PP9-PLUS",
    modelId: "ZZP",
    codeEAN13CharMaxLen: 12,
    codeITFCharMaxLen: 32,
    codeCode128CharMaxLen: 32,
    codeCode39CharMaxLen: 32,
    codeQRCharMaxLen: 122,
    codePDFCharMaxLen: 122,

    headersXlen: 40,
    footersXlen: 40,
    RifLen: 38,
    RazonSocialLen: 34,
    AdcInfoLen: 40,
    CommentsLen: 40,
    DescLen: 120,
  },
];

module.exports = devices;
